apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-web
spec:
  template:
    spec:
      initContainers:
        - name: bootstrap-sqlite
          image: quay.example.com/example-org/openshift-laravel-pgsql:latest
      containers:
        - name: app
          image: quay.example.com/example-org/openshift-laravel-pgsql:latest
